// @ts-check
/**
 * Summarise one Claude Code session transcript into what a retrospective needs:
 * the words the human actually typed, the moments they pushed back, and the
 * programs the agent improvised.
 *
 * Two kinds of noise are removed here rather than by the model, because both
 * actively corrupt the analysis they feed.
 *
 * **Harness text stored as user turns.** Slash-command bodies, skill
 * instructions, CLAUDE.md copies, hook output and task notifications are all
 * recorded as `user` messages although nobody typed them. Unfiltered they were
 * ~80% of one real corpus by volume and produced false correction hits in 18 of
 * 21 sessions. Newer transcripts label a typed turn with `origin.kind: "human"`
 * and injected ones with `isMeta`; older ones need the prefix heuristics below.
 *
 * **Self-referential sessions.** A kaizen run's own transcript contains the
 * kaizen procedure, which is full of correction vocabulary — so a retrospective
 * that reads itself scores as the most correction-heavy session every time.
 * Detection is by *command invocation*, never by directory name: a worktree
 * called `kaizen-…` can host a perfectly ordinary, very valuable session.
 */
import { statSync } from 'node:fs'
import { basename, dirname } from 'node:path'
import { scriptsInEntry } from './adhoc.mjs'
import { expandHome, messageText, readJsonl, repoRoot, toHomeRelative, toolResultText } from './lib.mjs'

// Paired tags whose entire contents are machine-generated.
const STRIP_TAGS = [
  'system-reminder',
  'ide_opened_file',
  'ide_selection',
  'ide_diagnostics',
  'EXTREMELY_IMPORTANT',
  'EXTREMELY-IMPORTANT',
  'SUBAGENT-STOP',
  'codegraph_context',
  'command-name',
  'command-message',
  'user-prompt-submit-hook',
  'task-notification',
  'local-command-caveat',
  'local-command-stdout',
  'local-command-stderr',
  'bash-stdout',
  'bash-stderr',
]
const escapeRe = (/** @type {string} */ s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
const TAG_ALT = STRIP_TAGS.map(escapeRe).join('|')
const TAG_RE = new RegExp(`<(?:${TAG_ALT})[^>]*>.*?</(?:${TAG_ALT})>`, 'gs')

// `<command-args>` and `<bash-input>` wrap what the human typed: keep the text.
const UNWRAP_RE = /<\/?(?:command-args|bash-input)[^>]*>/g
const COMMAND_NAME_RE = /<command-name>\s*\/?([^<\s]+)\s*<\/command-name>/g

// A message starting with any of these was injected by the harness.
const DROP_PREFIXES = [
  'Base directory for this skill:',
  'Codebase and user instructions are shown below',
  '## Context Usage',
  '<system-reminder>',
  '<task-notification>',
  'Caveat: The messages below were generated by the user',
  'This session is being continued from a previous conversation',
]
// A slash-command body renders as a markdown doc titled with the command.
const COMMAND_BODY_RE = /^#\s+\/[\w:-]+/
const IMAGE_ONLY_RE = /^\[Image #?\d*[^\]]*\]$/

// Tool-result text Claude Code writes when a human rejects a tool call. When
// they also typed why, it follows "the user said:" — the single most specific
// correction a transcript carries.
const USER_DENIAL_RE = /The user doesn't want to (?:proceed with this tool use|take this action)/
const DENIAL_REASON_RE = /the user said:\s*([\s\S]+)$/i
const CLASSIFIER_DENIAL_RE = /denied by the Claude Code auto mode classifier/
const WORKTREE_RE = /\/\.claude\/worktrees\/([^/]+)/

/**
 * Cheap lexical hints that a message is pushback. They only rank sessions for
 * reading; the model decides what actually happened. Kept here, not in the
 * skill text, so the procedure the model reads does not itself match them.
 */
const SIGNALS = /** @type {const} */ ({
  interrupt: /\[Request interrupted by user/,
  denial: /^\[denied /,
  correction:
    /(?:^no\b|\bno[,.!]\s|\bdon'?t\b|\bstop\b|\bwrong\b|that'?s not what|not what I (?:asked|meant|wanted)|\bI said\b|\bI told you\b|\byou should(?:n'?t)?\b|\binstead\b)/i,
  redo: /\b(?:undo|revert|go back|try again|start over|roll ?back|put it back)\b/i,
  quality: /\b(?:error|mistake|bug|broke|broken|missing|forgot|you missed|the real issue|actually|still (?:fails|broken|wrong))\b/i,
  convention: /(?:CLAUDE\.md|AGENTS\.md|\bthe (?:pattern|convention) is\b|\bwe don'?t do\b|\bwe always\b|\bwe never\b|\bfrom now on\b|\bgoing forward\b|\bin the future\b)/i,
})

export const LIMITS = {
  /** Characters kept per message; pasted logs are the usual overflow. */
  messageChars: 1500,
  /** Messages kept per session; flagged ones are kept first. */
  messages: 60,
  /** Script events kept per session; the true count rides beside the list. */
  scripts: 40,
}

/** @param {string} text */
function stripTags(text) {
  return text.replace(TAG_RE, '').replace(UNWRAP_RE, '').trim()
}

/** @param {string} raw */
function invokedCommands(raw) {
  const found = new Set()
  for (const m of raw.matchAll(COMMAND_NAME_RE)) {
    const name = m[1].toLowerCase()
    found.add(name)
    found.add(name.split(':').at(-1))
  }
  return found
}

/** @param {string} text */
function isBoilerplate(text) {
  return DROP_PREFIXES.some((p) => text.startsWith(p)) || COMMAND_BODY_RE.test(text) || IMAGE_ONLY_RE.test(text)
}

/** @param {string} text */
export function signalsFor(text) {
  return Object.entries(SIGNALS)
    .filter(([, re]) => re.test(text))
    .map(([k]) => k)
}

/** @param {string} text */
function capText(text) {
  const max = LIMITS.messageChars
  return text.length > max ? `${text.slice(0, max)}… [+${text.length - max} chars]` : text
}

/**
 * Keep every flagged message and fill the rest from the start and end of the
 * session — the ask is at the start, the verdict at the end.
 * @template {{ flags?: string[] }} M
 * @param {M[]} messages
 * @returns {{ kept: M[], omitted: number }}
 */
function selectMessages(messages) {
  const max = LIMITS.messages
  if (messages.length <= max) return { kept: messages, omitted: 0 }
  const keep = new Set()
  messages.forEach((m, i) => {
    if (m.flags?.length && keep.size < max) keep.add(i)
  })
  for (let lo = 0, hi = messages.length - 1; keep.size < max && lo <= hi; lo++, hi--) {
    keep.add(lo)
    if (keep.size < max) keep.add(hi)
  }
  const kept = messages.filter((_, i) => keep.has(i))
  return { kept, omitted: messages.length - kept.length }
}

/**
 * @typedef {object} Summary
 * @property {string} sessionId
 * @property {string} project  Repository (or directory) name the session ran in.
 * @property {string | null} worktree  Claude Code worktree name, when it ran in one.
 * @property {string} cwd
 * @property {string} repoRoot  The main checkout; its auto-memory dir is the one to write.
 * @property {string} title  The name the human sees: custom title over AI title.
 * @property {string} started
 * @property {string} ended
 * @property {string} path  Home-relative transcript path; the status key.
 * @property {number} bytes  Transcript size when read; a later, larger size means it resumed.
 * @property {number} [resumedFrom]  Byte offset this summary starts at, for a resumed session.
 * @property {string[]} commands  Slash commands and skills invoked.
 * @property {{ text: string, flags?: string[] }[]} messages  What the human typed, in order.
 * @property {number} omittedMessages
 * @property {{ user: number, classifier: number }} denials
 * @property {number} score  Rough pushback count, for ordering the reading.
 * @property {import('./adhoc.mjs').ScriptEvent[]} scripts
 * @property {number} scriptCount  Total before the per-session cap.
 */

/**
 * @param {string} jsonlPath
 * @param {{ from?: number }} [opts]  Only entries at or after byte offset `from`
 *   contribute messages and scripts; titles and cwd come from the whole file.
 * @returns {Summary | null}  null when nothing a human typed survives filtering.
 */
export function summarize(jsonlPath, { from = 0 } = {}) {
  const abs = expandHome(jsonlPath)
  const sessionId = basename(abs, '.jsonl')
  const bytes = statSync(abs).size
  let aiTitle = null
  let customTitle = null
  let cwd = null
  /** @type {string | null} */
  let worktree = null
  let started = ''
  let ended = ''
  /** @type {{ text: string, flags?: string[] }[]} */
  const messages = []
  const commands = new Set()
  const scripts = []
  let scriptCount = 0
  const denials = { user: 0, classifier: 0 }
  /** @type {Map<string, string>} */
  const toolNames = new Map()

  for (const { entry, offset } of readJsonl(abs)) {
    if (entry.isSidechain) continue
    if (typeof entry.timestamp === 'string') {
      if (!started) started = entry.timestamp
      ended = entry.timestamp
    }
    if (!cwd && typeof entry.cwd === 'string') cwd = entry.cwd
    // Sessions often start in the main checkout and enter a worktree later.
    if (!worktree && typeof entry.cwd === 'string') worktree = WORKTREE_RE.exec(entry.cwd)?.[1] ?? null

    // Claude Code shows customTitle over aiTitle, and the last rename wins.
    if (entry.type === 'custom-title') {
      const t = String(entry.customTitle ?? '').trim()
      if (t) customTitle = t
    }
    if (entry.type === 'ai-title' && !aiTitle && entry.aiTitle) aiTitle = String(entry.aiTitle)

    const content = entry.message?.content
    if (entry.type === 'assistant' && Array.isArray(content)) {
      for (const b of content) {
        if (b?.type !== 'tool_use') continue
        toolNames.set(b.id, b.name)
        // A skill the model invoked itself is as self-referential as a typed one.
        if (b.name === 'Skill' && typeof b.input?.skill === 'string') {
          const s = b.input.skill.toLowerCase()
          commands.add(s)
          commands.add(s.split(':').at(-1))
        }
      }
    }

    if (offset < from) continue

    for (const ev of scriptsInEntry(entry)) {
      scriptCount += 1
      if (scripts.length < LIMITS.scripts) scripts.push(ev)
    }

    if (entry.type !== 'user' || entry.isMeta || entry.isCompactSummary) continue

    if (Array.isArray(content)) {
      for (const b of content) {
        if (b?.type !== 'tool_result') continue
        const text = toolResultText(b.content)
        if (CLASSIFIER_DENIAL_RE.test(text) || String(entry.toolDenialKind ?? '').startsWith('automode')) {
          denials.classifier += 1
        } else if (USER_DENIAL_RE.test(text)) {
          denials.user += 1
          const reason = DENIAL_REASON_RE.exec(text)?.[1]?.trim()
          const tool = toolNames.get(b.tool_use_id) ?? 'tool'
          const line = `[denied ${tool}]${reason ? ` ${reason}` : ''}`
          messages.push({ text: capText(line), flags: signalsFor(line) })
        }
      }
    }

    const origin = entry.origin?.kind
    if (origin && origin !== 'human') continue
    const raw = messageText(content)
    if (!raw) continue
    for (const c of invokedCommands(raw)) commands.add(c)
    const cleaned = stripTags(raw)
    if (!cleaned || isBoilerplate(cleaned)) continue
    const flags = signalsFor(cleaned)
    messages.push(flags.length ? { text: capText(cleaned), flags } : { text: capText(cleaned) })
  }

  if (messages.length === 0) return null

  const { kept, omitted } = selectMessages(messages)
  const dir = cwd ?? dirname(abs)
  const root = cwd ? repoRoot(cwd) : dir
  const score =
    messages.filter((m) => m.flags?.some((f) => f !== 'quality')).length + denials.user * 2

  return {
    sessionId,
    project: basename(root),
    worktree,
    cwd: dir,
    repoRoot: root,
    title: customTitle || aiTitle || '(untitled)',
    started,
    ended,
    path: toHomeRelative(abs),
    bytes,
    ...(from > 0 ? { resumedFrom: from } : {}),
    commands: [...commands].sort(),
    messages: kept,
    omittedMessages: omitted,
    denials,
    score,
    scripts,
    scriptCount,
  }
}

/**
 * True when analysing this session would mean analysing kaizen's own text.
 * @param {Summary} s
 * @param {string[]} skipCommands
 */
export function isSelfReferential(s, skipCommands) {
  const skip = new Set(skipCommands.map((c) => c.toLowerCase()))
  if (s.commands.some((c) => skip.has(c))) return true
  // A resumed run can lose its command tag; the name it stamped on itself stays.
  const title = s.title.toLowerCase()
  return [...skip].some((c) => new RegExp(`^${escapeRe(c)}\\b`).test(title))
}
